# Generated by Django 2.2.4 on 2019-08-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad_post',
            options={'ordering': ['-id']},
        ),
    ]
