# Generated by Django 2.2.4 on 2019-08-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_post', '0002_auto_20190813_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_post',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
