# Generated by Django 2.2.4 on 2019-08-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('post_number', models.CharField(max_length=7)),
                ('homepage', models.TextField()),
                ('number', models.TextField()),
                ('introduce', models.TextField()),
            ],
        ),
    ]
