# Generated by Django 2.2.4 on 2019-08-19 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190819_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_comment',
            name='info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Info'),
            preserve_default=False,
        ),
    ]
