# Generated by Django 2.2.4 on 2019-08-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190819_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_comment',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Info'),
        ),
    ]
