# Generated by Django 2.2.4 on 2019-08-23 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190823_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='rate_ave',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='rate_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='map_comment',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Info'),
        ),
        migrations.AlterField(
            model_name='map_comment',
            name='rate',
            field=models.CharField(choices=[('★☆☆☆☆', '★☆☆☆☆'), ('★★☆☆☆', '★★☆☆☆'), ('★★★☆☆', '★★★☆☆'), ('★★★★☆', '★★★★☆'), ('★★★★★', '★★★★★')], max_length=5),
        ),
    ]
